// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/mediatranslation/v1beta1/media_translation.proto

package com.google.cloud.mediatranslation.v1beta1;

public final class MediaTranslationProto {
  private MediaTranslationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_mediatranslation_v1beta1_TranslateSpeechConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_mediatranslation_v1beta1_TranslateSpeechConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResult_TextTranslationResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResult_TextTranslationResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n=google/cloud/mediatranslation/v1beta1/" +
      "media_translation.proto\022%google.cloud.me" +
      "diatranslation.v1beta1\032\034google/api/annot" +
      "ations.proto\032\037google/api/field_behavior." +
      "proto\032\027google/rpc/status.proto\032\027google/a" +
      "pi/client.proto\"\256\001\n\025TranslateSpeechConfi" +
      "g\022\033\n\016audio_encoding\030\001 \001(\tB\003\340A\002\022!\n\024source" +
      "_language_code\030\002 \001(\tB\003\340A\002\022!\n\024target_lang" +
      "uage_code\030\003 \001(\tB\003\340A\002\022\036\n\021sample_rate_hert" +
      "z\030\004 \001(\005B\003\340A\001\022\022\n\005model\030\005 \001(\tB\003\340A\001\"\230\001\n\036Str" +
      "eamingTranslateSpeechConfig\022W\n\014audio_con" +
      "fig\030\001 \001(\0132<.google.cloud.mediatranslatio" +
      "n.v1beta1.TranslateSpeechConfigB\003\340A\002\022\035\n\020" +
      "single_utterance\030\002 \001(\010B\003\340A\001\"\262\001\n\037Streamin" +
      "gTranslateSpeechRequest\022a\n\020streaming_con" +
      "fig\030\001 \001(\0132E.google.cloud.mediatranslatio" +
      "n.v1beta1.StreamingTranslateSpeechConfig" +
      "H\000\022\027\n\raudio_content\030\002 \001(\014H\000B\023\n\021streaming" +
      "_request\"\364\001\n\036StreamingTranslateSpeechRes" +
      "ult\022~\n\027text_translation_result\030\001 \001(\0132[.g" +
      "oogle.cloud.mediatranslation.v1beta1.Str" +
      "eamingTranslateSpeechResult.TextTranslat" +
      "ionResultH\000\032H\n\025TextTranslationResult\022\030\n\013" +
      "translation\030\001 \001(\tB\003\340A\003\022\025\n\010is_final\030\002 \001(\010" +
      "B\003\340A\003B\010\n\006result\"\362\002\n StreamingTranslateSp" +
      "eechResponse\022&\n\005error\030\001 \001(\0132\022.google.rpc" +
      ".StatusB\003\340A\003\022Z\n\006result\030\002 \001(\0132E.google.cl" +
      "oud.mediatranslation.v1beta1.StreamingTr" +
      "anslateSpeechResultB\003\340A\003\022w\n\021speech_event" +
      "_type\030\003 \001(\0162W.google.cloud.mediatranslat" +
      "ion.v1beta1.StreamingTranslateSpeechResp" +
      "onse.SpeechEventTypeB\003\340A\003\"Q\n\017SpeechEvent" +
      "Type\022!\n\035SPEECH_EVENT_TYPE_UNSPECIFIED\020\000\022" +
      "\033\n\027END_OF_SINGLE_UTTERANCE\020\0012\314\002\n\030SpeechT" +
      "ranslationService\022\332\001\n\030StreamingTranslate" +
      "Speech\022F.google.cloud.mediatranslation.v" +
      "1beta1.StreamingTranslateSpeechRequest\032G" +
      ".google.cloud.mediatranslation.v1beta1.S" +
      "treamingTranslateSpeechResponse\")\202\323\344\223\002#\"" +
      "\036/v1/documents:analyzeSentiment:\001*(\0010\001\032S" +
      "\312A\037mediatranslation.googleapis.com\322A.htt" +
      "ps://www.googleapis.com/auth/cloud-platf" +
      "ormB\231\002\n)com.google.cloud.mediatranslatio" +
      "n.v1beta1B\025MediaTranslationProtoP\001ZUgoog" +
      "le.golang.org/genproto/googleapis/cloud/" +
      "mediatranslation/v1beta1;mediatranslatio" +
      "n\370\001\001\252\002%Google.Cloud.MediaTranslation.V1B" +
      "eta1\312\002%Google\\Cloud\\MediaTranslation\\V1b" +
      "eta1\352\002(Google::Cloud::MediaTranslation::" +
      "V1beta1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.rpc.StatusProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
        });
    internal_static_google_cloud_mediatranslation_v1beta1_TranslateSpeechConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_mediatranslation_v1beta1_TranslateSpeechConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_mediatranslation_v1beta1_TranslateSpeechConfig_descriptor,
        new java.lang.String[] { "AudioEncoding", "SourceLanguageCode", "TargetLanguageCode", "SampleRateHertz", "Model", });
    internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechConfig_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechConfig_descriptor,
        new java.lang.String[] { "AudioConfig", "SingleUtterance", });
    internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechRequest_descriptor,
        new java.lang.String[] { "StreamingConfig", "AudioContent", "StreamingRequest", });
    internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResult_descriptor,
        new java.lang.String[] { "TextTranslationResult", "Result", });
    internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResult_TextTranslationResult_descriptor =
      internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResult_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResult_TextTranslationResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResult_TextTranslationResult_descriptor,
        new java.lang.String[] { "Translation", "IsFinal", });
    internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_cloud_mediatranslation_v1beta1_StreamingTranslateSpeechResponse_descriptor,
        new java.lang.String[] { "Error", "Result", "SpeechEventType", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.oauthScopes);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
